"""add Patient profile

Revision ID: 06c01bac3323
Revises: e92d58c4860d
Create Date: 2026-03-22 13:46:06.773673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '06c01bac3323'
down_revision: Union[str, None] = 'e92d58c4860d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patientprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('blood_pressure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('existing_diseases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('smoking', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alcohol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientprofile_user_id'), 'patientprofile', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patientprofile_user_id'), table_name='patientprofile')
    op.drop_table('patientprofile')
    # ### end Alembic commands ###
