"""Add SpentNafScore table

Revision ID: 18327d56b891
Revises: 77246656a465
Create Date: 2026-03-15 14:50:24.055522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '18327d56b891'
down_revision: Union[str, None] = '77246656a465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_answer_spent', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('spent_score', sa.Integer(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=True),
    sa.Column('user_answer_naf', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('naf_score', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer_table')
    # ### end Alembic commands ###
