"""add volume to foodlog

Revision ID: 21ed449dd0ea
Revises: 61ac0ba6157a
Create Date: 2026-04-05 12:52:35.906908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ed449dd0ea'
down_revision: Union[str, None] = '61ac0ba6157a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodlog', sa.Column('volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodlog', 'volume')
    # ### end Alembic commands ###
