"""add realname surname

Revision ID: 77246656a465
Revises: 9bf2b5d65c96
Create Date: 2026-03-08 21:02:27.452368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '77246656a465'
down_revision: Union[str, None] = '9bf2b5d65c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###
