"""add foodlog and dailycaloriegoal

Revision ID: ab0603ed8136
Revises: 37792cb99200
Create Date: 2026-03-15 23:08:45.960244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ab0603ed8136'
down_revision: Union[str, None] = '37792cb99200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailycaloriegoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailycaloriegoal_user_id'), 'dailycaloriegoal', ['user_id'], unique=True)
    op.create_table('foodlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('meal_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eaten_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodlog_user_id'), 'foodlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foodlog_user_id'), table_name='foodlog')
    op.drop_table('foodlog')
    op.drop_index(op.f('ix_dailycaloriegoal_user_id'), table_name='dailycaloriegoal')
    op.drop_table('dailycaloriegoal')
    # ### end Alembic commands ###
