"""fix foodlog

Revision ID: baf67f9c17cd
Revises: c6aba8411d08
Create Date: 2026-03-22 21:33:31.117978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'baf67f9c17cd'
down_revision: Union[str, None] = 'c6aba8411d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Clean bad data first
    op.execute("""
    DELETE FROM foodlog
    WHERE user_id NOT IN (SELECT id FROM "user")
    """)

    # 2. Then add foreign key
    op.create_table('exerciselog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('logged_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exerciselog_user_id'), 'exerciselog', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dailycaloriegoal', 'user', ['user_id'], ['id'])
    # protein
    op.add_column('foodlog', sa.Column('protein', sa.Float(), nullable=True))
    op.execute("UPDATE foodlog SET protein = 0 WHERE protein IS NULL")
    op.alter_column('foodlog', 'protein', nullable=False)

    # sodium
    op.add_column('foodlog', sa.Column('sodium', sa.Float(), nullable=True))
    op.execute("UPDATE foodlog SET sodium = 0 WHERE sodium IS NULL")
    op.alter_column('foodlog', 'sodium', nullable=False)

    # potassium
    op.add_column('foodlog', sa.Column('potassium', sa.Float(), nullable=True))
    op.execute("UPDATE foodlog SET potassium = 0 WHERE potassium IS NULL")
    op.alter_column('foodlog', 'potassium', nullable=False)

    # phosphorus
    op.add_column('foodlog', sa.Column('phosphorus', sa.Float(), nullable=True))
    op.execute("UPDATE foodlog SET phosphorus = 0 WHERE phosphorus IS NULL")
    op.alter_column('foodlog', 'phosphorus', nullable=False)
    op.alter_column('foodlog', 'calories',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('foodlog', 'eaten_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.create_foreign_key(None, 'foodlog', 'user', ['user_id'], ['id'])
    op.alter_column('patientprofile', 'existing_diseases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patientprofile', 'existing_diseases',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_constraint(None, 'foodlog', type_='foreignkey')
    op.alter_column('foodlog', 'eaten_date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('foodlog', 'calories',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('foodlog', 'phosphorus')
    op.drop_column('foodlog', 'potassium')
    op.drop_column('foodlog', 'sodium')
    op.drop_column('foodlog', 'protein')
    op.drop_constraint(None, 'dailycaloriegoal', type_='foreignkey')
    op.drop_index(op.f('ix_exerciselog_user_id'), table_name='exerciselog')
    op.drop_table('exerciselog')
    # ### end Alembic commands ###
