"""fix bloodtype model

Revision ID: c6aba8411d08
Revises: 06c01bac3323
Create Date: 2026-03-22 20:52:53.037117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c6aba8411d08'
down_revision: Union[str, None] = '06c01bac3323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bloodtest', sa.Column('serum_albumin', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('npcr', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('bun', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('creatinine', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('cholesterol', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('hemoglobin', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('hematocrit', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('potassium', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('phosphorus', sa.Float(), nullable=True))
    op.add_column('bloodtest', sa.Column('bicarbonate', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'bloodtest', 'user', ['user_id'], ['id'])
    op.drop_column('bloodtest', 'blood_level')
    op.execute(
"""
ALTER TABLE user_answer_table
ALTER COLUMN user_answer_naf
TYPE JSON
USING to_json(user_answer_naf)
"""
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answer_table', 'user_answer_naf',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.add_column('bloodtest', sa.Column('blood_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bloodtest', type_='foreignkey')
    op.drop_column('bloodtest', 'bicarbonate')
    op.drop_column('bloodtest', 'phosphorus')
    op.drop_column('bloodtest', 'potassium')
    op.drop_column('bloodtest', 'hematocrit')
    op.drop_column('bloodtest', 'hemoglobin')
    op.drop_column('bloodtest', 'cholesterol')
    op.drop_column('bloodtest', 'creatinine')
    op.drop_column('bloodtest', 'bun')
    op.drop_column('bloodtest', 'npcr')
    op.drop_column('bloodtest', 'serum_albumin')
    # ### end Alembic commands ###
