"""remove activity level and add urine amount to pateint profile

Revision ID: cf5eb42fe2a2
Revises: e2ee4eaa7525
Create Date: 2026-04-04 16:36:36.727261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5eb42fe2a2'
down_revision: Union[str, None] = 'e2ee4eaa7525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientprofile', sa.Column('urine_amount', sa.Float(), nullable=True))
    op.drop_column('patientprofile', 'activity_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientprofile', sa.Column('activity_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('patientprofile', 'urine_amount')
    # ### end Alembic commands ###
