"""add dailysetup table using datetime now

Revision ID: dccc439c13bb
Revises: e9a0c084273b
Create Date: 2026-04-06 22:35:13.436072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dccc439c13bb'
down_revision: Union[str, None] = 'e9a0c084273b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dailysetup', 'setup_date',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index('ix_dailysetup_setup_date', table_name='dailysetup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dailysetup_setup_date', 'dailysetup', ['setup_date'], unique=False)
    op.alter_column('dailysetup', 'setup_date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
