"""empty message

Revision ID: e2ee4eaa7525
Revises: b47aae31be7f
Create Date: 2026-04-02 16:50:11.346148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ee4eaa7525'
down_revision: Union[str, None] = 'b47aae31be7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer_table', sa.Column('naf_score_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answer_table', 'naf_score_breakdown')
    # ### end Alembic commands ###
