"""add dailysetup table

Revision ID: e9a0c084273b
Revises: 21ed449dd0ea
Create Date: 2026-04-06 22:23:57.442775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a0c084273b'
down_revision: Union[str, None] = '21ed449dd0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailysetup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('urine_amount', sa.Float(), nullable=True),
    sa.Column('setup_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailysetup_setup_date'), 'dailysetup', ['setup_date'], unique=False)
    op.create_index(op.f('ix_dailysetup_user_id'), 'dailysetup', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailysetup_user_id'), table_name='dailysetup')
    op.drop_index(op.f('ix_dailysetup_setup_date'), table_name='dailysetup')
    op.drop_table('dailysetup')
    # ### end Alembic commands ###
